name: myenv
channels:
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - cmake
  - pip
  - pip:
    - face_recognition
    - opencv-python
    - dlib==19.22
